name: xcom2-automation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - opencv
  - numpy
  - pyobjc-framework-ScriptingBridge
  - pillow
  - pyautogui
  - pynput
  - requests
  - pip:
      - opencv-python
