name: xcom2-automation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - opencv
  - pytesseract
  - pillow
  - stable-baselines3
  - gymnasium
  - screeninfo
  - pip
  - pip:
      - pyautogui
      - tesseract
      - tensorflow
